{% set name = "yourdfpy" %}
{% set version = "0.0.56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yourdfpy-{{ version }}.tar.gz
  sha256: 6075b643482b5e4c406fa053597484c450c8823058d4068c091f54238808ab1a

build:
  noarch: python
  entry_points:
    - yourdfpy = yourdfpy.viz:run
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - lxml
    - trimesh >=3.11.2
    - numpy
    - six

test:
  imports:
    - yourdfpy
  commands:
    - pip check
    - yourdfpy --help
  requires:
    - pip
    - setuptools
    - python {{ python_min }}

about:
  home: https://github.com/clemense/yourdfpy/
  summary: A simpler and easier-to-use library for loading, manipulating, saving, and visualizing URDF files.
  dev_url: https://github.com/clemense/yourdfpy/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ruben-arts
